name: python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        echo $(pwd)
        ls
        pip install --upgrade pip
        pip install .[tests]
    - name: Checkout nomad
      with:
        repository: nomad-coe/nomad
        path: ./nomad
    - name: Install nomad
      run: |
        echo $(pwd)
        ls
        pip install ./nomad[parsing]
´   - name: pycodestyle
      run: |
        python -m pycodestyle --ignore=E501,E701,E731 *parsers tests
    - name: pylint
      run: |
        python -m pylint --load-plugins=nomad.metainfo.pylint_plugin *parsers tests
    - name: mypy
      run: |
        python -m mypy --ignore-missing-imports --follow-imports=silent --no-strict-optional *parsers tests
    - name: Test with pytest
      run: |
        python -m pytest -sv tests
