name: python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        git config --global url.https://github.com/.insteadOf git://github.com/
        git clone https://github.com/nomad-coe/nomad.git
        pip install --upgrade pip
        pip install .[tests]
        pip install ./nomad[parsing]
    - name: pycodestyle
      run: |
        python -m pycodestyle --ignore=E501,E701,E731 *parsers tests
    - name: pylint
      run: |
        python -m pylint --load-plugins=nomad.metainfo.pylint_plugin *parsers tests
    - name: mypy
      run: |
        python -m mypy --ignore-missing-imports --follow-imports=silent --no-strict-optional *parsers tests
    - name: Test with pytest
      run: |
        python -m pytest -sv tests
